services:
  - type: web
    name: telegram-bot-host
    env: docker
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8109732136:AAGoVJURJtbUJuqcN84ciC5We2Ni3W4OMYM"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheck:
      path: /health